---
spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  web:
    resources:
      add-mappings: false
  cache:
    ehcache:
      config: classpath:ehcache.xml
  profiles:
    group:
      local: "local-envs,local-db"
      dev: ""
      production: ""
    active: local
security:
  jwt:
    key-value: "2AA4B45D5FB9FF29B722A57E3E9FAAF4F2DC33326953338C5F9B92783E"
---
# local env
spring.config.activate.on-profile: local-envs

---
# local db
spring.config.activate.on-profile: local-db

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/MY_SECURITY?useUnicode=yes&characterEncoding=UTF-8"
    username: "root"
    password: "nextage2020!"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: 127.0.0.1
    port: 6379
